# This is a basic workflow to help you get started with Actions

name: deploy-gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.18.2
  
      - name: Run echo environment
        run: echo `node -v`

      - name: Run package install
        run: |
          npm install
          npm run ginstall

      - name: Prepare Run module gh-pages to deploy github and coding
        run: echo `npm run gh-pages-dev -- -V`

      - name: Run deploy-github-gh-pages
        run: npm run deploy -- -r 'https://${{secrets.USER_TOKEN}}@github.com/Ariescat/Metis-Awesome.git' -u 'github-actions-bot <${{secrets.EMAIL}}>' -m 'github-actions-bot Updates'

      - name: Run deploy-coding-master
        # 用户名密码中一定要转义 @符号 转码后变成了%40  See:https://blog.csdn.net/u012447791/article/details/118225605
        # eg. https://username:password@127.0.0.1/res/res.git
        run: npm run deploy -- -b master -r 'https://${{secrets.CODING_USER_PASS}}@e.coding.net/${{secrets.CODING_REPO}}' -u 'github-actions-bot <${{secrets.EMAIL}}>' -m 'github-actions-bot Updates'
